//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CST_INV_DTL
    {
        public int OrderDetailID { get; set; }
        public string OrderID { get; set; }
        public string RFID { get; set; }
        public string Location { get; set; }
        public string PalletNo { get; set; }
        public string PalletRFID { get; set; }
        public string Date { get; set; }
        public string LotNo { get; set; }
        public string PNo { get; set; }
        public string Weight { get; set; }
        public string Length { get; set; }
        public string Order { get; set; }
        public string InternalOrder { get; set; }
        public string WKNo { get; set; }
        public string Fabric { get; set; }
        public string ColorCode { get; set; }
        public string Color { get; set; }
        public string Status { get; set; }
        public string Lot { get; set; }
    }
}
