//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CST_USER_HIST
    {
        public int SID { get; set; }
        public string UserProfileID { get; set; }
        public string FunctionName { get; set; }
        public string Parameter { get; set; }
        public string NewValue { get; set; }
        public string OldValue { get; set; }
        public string CreateTime { get; set; }
    }
}
