//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CST_PALLET
    {
        public string PalletID { get; set; }
        public string PalletNumber { get; set; }
        public string PalletTypeID { get; set; }
        public string Status { get; set; }
        public string RFIDID { get; set; }
        public string CardNumber { get; set; }
        public string Description { get; set; }
        public int Active { get; set; }
        public int IsDelete { get; set; }
        public string CreateTime { get; set; }
        public string LastUpdateTime { get; set; }
    }
}
