//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CST_MENU_GRP
    {
        public string MenuGroupID { get; set; }
        public string UserGroupID { get; set; }
        public string MainMenuID { get; set; }
        public string MainMenuName { get; set; }
        public string SubMenuID { get; set; }
        public string SubMenuName { get; set; }
        public string MinorMenuID { get; set; }
        public string MinorMenuName { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
