//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CST_WAREHOUSE_LOG
    {
        public string WareHouseDataLogID { get; set; }
        public string DeviceName { get; set; }
        public string PalletNumber { get; set; }
        public string PalletTypeID { get; set; }
        public string ParkingBlockID { get; set; }
        public string RFIDID { get; set; }
        public string StockInTime { get; set; }
        public string StockOutTime { get; set; }
        public string Quantity { get; set; }
        public string PreGateReaderNumber { get; set; }
        public string LastGateReaderNumber { get; set; }
        public string WO { get; set; }
        public string Lot { get; set; }
        public string OverTime { get; set; }
        public string MailFlag { get; set; }
        public string LastUpdateTime { get; set; }
        public string WarningDay { get; set; }
        public string StockIn { get; set; }
        public string StockOut { get; set; }
        public string RFID { get; set; }
        public string WKNo { get; set; }
        public string LotNo { get; set; }
        public string Order { get; set; }
        public string InternalOrder { get; set; }
        public string Fabric { get; set; }
        public string Color { get; set; }
        public string Width { get; set; }
        public string YdWt { get; set; }
        public string Weight { get; set; }
        public string Length { get; set; }
        public string PNo { get; set; }
        public string Date { get; set; }
        public string ColorCode { get; set; }
    }
}
