//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CST_STORAGE_PARKINGBLOCK
    {
        public string ParkingBlockID { get; set; }
        public string ParkingBlockName { get; set; }
        public string StorageID { get; set; }
        public string FieldID { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string CreateTime { get; set; }
        public string LastUpdateTime { get; set; }
    }
}
