//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CST_RFID_ERROR_LOG
    {
        public int No { get; set; }
        public string OrderNo { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string ErrorMessage { get; set; }
        public string PalletRFID { get; set; }
        public string RFID { get; set; }
        public string GateReaderNumber { get; set; }
        public string UpLoadType { get; set; }
        public string Lot { get; set; }
        public string Remark { get; set; }
    }
}
