//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_Retail
    {
        public int RetailID { get; set; }
        public string RetailName { get; set; }
        public string RetailSuperVisor { get; set; }
        public string RetailAdd { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Descript { get; set; }
        public string Note { get; set; }
    }
}
