//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseServerEntities : DbContext
    {
        public WarehouseServerEntities()
            : base("name=WarehouseServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CST_ALARM> CST_ALARM { get; set; }
        public virtual DbSet<CST_BEACON> CST_BEACON { get; set; }
        public virtual DbSet<CST_BEACON_LOCATION> CST_BEACON_LOCATION { get; set; }
        public virtual DbSet<CST_BEACON_PARKINGBLOCK> CST_BEACON_PARKINGBLOCK { get; set; }
        public virtual DbSet<CST_CARD> CST_CARD { get; set; }
        public virtual DbSet<CST_CARD_PATH> CST_CARD_PATH { get; set; }
        public virtual DbSet<CST_CARD_PATH_HIST> CST_CARD_PATH_HIST { get; set; }
        public virtual DbSet<CST_EXCEPTION_LOG> CST_EXCEPTION_LOG { get; set; }
        public virtual DbSet<CST_FIELD_MAP> CST_FIELD_MAP { get; set; }
        public virtual DbSet<CST_GATE_READER> CST_GATE_READER { get; set; }
        public virtual DbSet<CST_INV> CST_INV { get; set; }
        public virtual DbSet<CST_INV_DTL> CST_INV_DTL { get; set; }
        public virtual DbSet<CST_MAIL_GRP> CST_MAIL_GRP { get; set; }
        public virtual DbSet<CST_MAIL_GRP_DTL> CST_MAIL_GRP_DTL { get; set; }
        public virtual DbSet<CST_MAIL_LOG> CST_MAIL_LOG { get; set; }
        public virtual DbSet<CST_MENU_GRP> CST_MENU_GRP { get; set; }
        public virtual DbSet<CST_MENU_MAIN> CST_MENU_MAIN { get; set; }
        public virtual DbSet<CST_MENU_MINOR> CST_MENU_MINOR { get; set; }
        public virtual DbSet<CST_MENU_SUB> CST_MENU_SUB { get; set; }
        public virtual DbSet<CST_ORDER_TYPE> CST_ORDER_TYPE { get; set; }
        public virtual DbSet<CST_PALLET> CST_PALLET { get; set; }
        public virtual DbSet<CST_PALLET_TYPE> CST_PALLET_TYPE { get; set; }
        public virtual DbSet<CST_RFID> CST_RFID { get; set; }
        public virtual DbSet<CST_RFID_ERROR_LOG> CST_RFID_ERROR_LOG { get; set; }
        public virtual DbSet<CST_SER_INV> CST_SER_INV { get; set; }
        public virtual DbSet<CST_SER_INV_DTL> CST_SER_INV_DTL { get; set; }
        public virtual DbSet<CST_STOCK_OUT> CST_STOCK_OUT { get; set; }
        public virtual DbSet<CST_STOCK_OUT_LOG> CST_STOCK_OUT_LOG { get; set; }
        public virtual DbSet<CST_STORAGE_PARKINGBLOCK> CST_STORAGE_PARKINGBLOCK { get; set; }
        public virtual DbSet<CST_USER_GRP> CST_USER_GRP { get; set; }
        public virtual DbSet<CST_USER_HIST> CST_USER_HIST { get; set; }
        public virtual DbSet<CST_USER_PROFILE> CST_USER_PROFILE { get; set; }
        public virtual DbSet<CST_WAREHOUSE> CST_WAREHOUSE { get; set; }
        public virtual DbSet<CST_WAREHOUSE_HIST> CST_WAREHOUSE_HIST { get; set; }
        public virtual DbSet<CST_WAREHOUSE_LOG> CST_WAREHOUSE_LOG { get; set; }
        public virtual DbSet<POS_EmpGroup> POS_EmpGroup { get; set; }
        public virtual DbSet<POS_Employee> POS_Employee { get; set; }
        public virtual DbSet<POS_EmpPermissions> POS_EmpPermissions { get; set; }
        public virtual DbSet<POS_EmpProgram> POS_EmpProgram { get; set; }
        public virtual DbSet<POS_OrganizationChart> POS_OrganizationChart { get; set; }
        public virtual DbSet<POS_Product> POS_Product { get; set; }
        public virtual DbSet<POS_ProductCatrgory> POS_ProductCatrgory { get; set; }
        public virtual DbSet<POS_Retail> POS_Retail { get; set; }
        public virtual DbSet<POS_RetailPurchase> POS_RetailPurchase { get; set; }
        public virtual DbSet<POS_RetailSale> POS_RetailSale { get; set; }
        public virtual DbSet<POS_Supplier> POS_Supplier { get; set; }
        public virtual DbSet<POS_USER_PROFILE> POS_USER_PROFILE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TEMP_ERP_INV_DTL> TEMP_ERP_INV_DTL { get; set; }
        public virtual DbSet<POS_SaleList> POS_SaleList { get; set; }
        public virtual DbSet<POS_Stock> POS_Stock { get; set; }
        public virtual DbSet<POS_UserLogin> POS_UserLogin { get; set; }
        public virtual DbSet<TEMP_ERP_STOCK_OUT> TEMP_ERP_STOCK_OUT { get; set; }
        public virtual DbSet<vw_Lots> vw_Lots { get; set; }
        public virtual DbSet<vw_Record> vw_Record { get; set; }
        public virtual DbSet<vw_RFIDLog> vw_RFIDLog { get; set; }
    }
}
